### ISSUE TITLE
Still keep the previous detailes

### ISSUE THREAD

**Issue by michaelm-88** [AlexPerathoner/Sessions#10]

**Comment by michaelm-88** [comment]
Hi 

I have 2 sso accounts  and when I click private , it is open new private windows but still got the details from my previous window 
that will good if you can make it  to open an new private session in the same window like SessionBox

**Comment by michaelm-88** [comment]
@AlexPerathoner  ??

**Comment by AlexPerathoner** [comment]
Sorry but I can't understand what your issue is. Can you please try to explain it again?
