### ISSUE TITLE
Make icon grey like native icons

### ISSUE THREAD

**Issue by olitus** [AlexPerathoner/Sessions#11]
Thank you for an amazing extension! I was looking for something similar for way too long.
I would like to ask if possible to make the icon color grey to blend better to the standard apple icons.
Or at least add an option to choose the color for the icon.

I can contribute the necessary change for this, if you will guide me slightly.

Here the icon is blue:
<img width="320" alt="Screen Shot 2021-02-27 at 5 39 20 PM" src="https://user-images.githubusercontent.com/5354501/109402295-ba841780-7922-11eb-8f49-88273c1897d5.png">

**Comment by AlexPerathoner** [comment]
Looks like a new characteristic of MacOS Big Sur... will take a look at it

**Comment by AlexPerathoner** [comment]
Watching the WWDC this is what I've found: the blueness of the icon means that the extension is loaded and active in the currently viewed page. Unfortunately, this isn't configurable.

**Comment by olitus** [comment]
This extension makes the icon grey https://github.com/adguardteam/adguardforsafari?utm_source=safari_extension&utm_medium=options_screen&utm_campaign=github#

**Comment by AlexPerathoner** [comment]
Double checked this.
This is what I've found out:

> The icon turns blue / accent tinted when the extension has access to the current page. This is by design, and informs the user that the extension is active. If your extension supplies a color icon, the colored icon will be used and not tinted. In your case, you could use a yellow light bulb, and we would use that, and grayscale it when the extension is inactive.

[source](https://developer.apple.com/forums/thread/651500)
