### ISSUE TITLE
MacOS Sonoma support

### ISSUE THREAD

**Issue by ade-x1** [AlexPerathoner/Sessions#17]
Hi Alex & everyone,
I've just updated to Sonoma and I noticed that Sessions no longer works for some reason. Once I try to select any of the sessions I've created nothing happens.

Anyone else is experiencing the same issue?

**Comment by ade-x1** [comment]
Hi Alex,
thank you for your reply!
I'm aware of Safari's group tabs feature, but I've always used your extensions and I still prefer it nowadays 😄. I hate the fact that Safari's group tabs it's always set on "auto update" and if I close one tab by mistake is lost, while in Sessions whatever is saved in the group stays there. Anyway I made this screen recording for you, after I click the icon I can see my sessions just fine but I am not able to click on any of those, they simply don't open. 
If I must do the switch to group tabs, I regretfully will, but I have no idea how to export those.

https://github.com/AlexPerathoner/Sessions/assets/59267060/1ed0c14e-8343-4396-befe-54f27f138d6b

**Comment by AlexPerathoner** [comment]
Quanta pulizia da fare xD
If you like it so much I'll have to take a look at it!
In the meantime, you can right click on a session and select export (last option) to save a json file with all the tabs. You can open it with any text editor. At least you can access the saved tabs

**Comment by ade-x1** [comment]
Troppa! xD
Many thanks, I was able to export the sessions data easily and I can go back to work on what was left pending.
If you have time to lose and want to check if that's an easy fix, I'd love to keep using your extension :D. Otherwise if you have to check this only for me and it requires too much time, don't worry I'll just give up and move to Safari group tabs

**Comment by AlexPerathoner** [comment]
I think I've fixed it. Let me know if it works

[Sessions.zip](https://github.com/AlexPerathoner/Sessions/files/12750819/Sessions.zip)

**Comment by ade-x1** [comment]
You did it! It works like a charm! Thank you very much

**Comment by belebeich** [comment]
Hi Alex, I've been using the same Safari App API to retrieve windows with containing tabs/pages in my own app. However, in Safari 17, it only returns loaded (you need to click on every unloaded tab to make it active) pages. On the other hand, Web Extensions work as expected (I don't think it's a permissions/privacy issue). It seems like Apple broke it...
