### ISSUE TITLE
Restoration of Pinned Tabs

### ISSUE THREAD

**Issue by alladinian** [AlexPerathoner/Sessions#3]
Hi there, great extension!
One minor annoyance though is that sessions are saving the pinned tabs as well, so when restoring them you end up with a window with `|- pinned_tabs - restored_pinned_tabs - other_tabs -|` which can be a little problematic if you got a fairly large amount of pinned tabs.

**Comment by AlexPerathoner** [comment]
I have to admit that I already knew about this issue... as this application was initially just for personal use and I don't use pinned tabs I just ignored the problem.
I'm sorry to hear that it's causing you problems. I'm already working on a fix.

**Comment by AlexPerathoner** [comment]
I've just released a new version which should fix this issue. Let me know if you have any problems with it: https://github.com/AlexPerathoner/Sessions/releases/latest

**Comment by alladinian** [comment]
Thanks man! That was really fast 🍻
