### ISSUE TITLE
Pinned tabs

### ISSUE THREAD

**Issue by novelwithsoftware** [AlexPerathoner/Sessions#4]
Pinned tabs are now no longer part of sessions and will therefore be ignored when restoring a session,

pls add options, Pinned tabs part of sessions, now Pinned tabs, don't have sessions.

**Comment by AlexPerathoner** [comment]
I'll add an option. Had no idea someone could be interested in saving pinned tabs, too.
Until I draft a new release you can use the old version to have the pinned tabs to be saved.
