### ISSUE TITLE
Issues with auto-saving

### ISSUE THREAD

**Issue by elsurudo** [AlexPerathoner/Sessions#9]
Hi,

I'm using the latest version, but find that when using the auto-save feature, new tabs are not saving.

The session has the green icon beside it, but no matter how long I wait, new tabs are not saved. Furthermore, even "replacing" the session doesn't save the new tabs, which is strange.

Any ideas?

**Comment by AlexPerathoner** [comment]
The auto-save feature is based on the replace function. So at least it makes sense that if the first is not working, neither is the second.
The fact that the replace feature is not working is indeed really strange.

You can save new sessions without any problem, right?

**Comment by AlexPerathoner** [comment]
Update: I've found the bug. As always it's an incredibly stupid mistake (sorry). Unfortunately it affects more stuff than I would like to admit so I'll release a fix only tomorrow morning.

**Comment by AlexPerathoner** [comment]
https://github.com/AlexPerathoner/Sessions/releases/tag/v1.6.1
